# Generated by Django 2.1.4 on 2018-12-31 13:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=100)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('date_published', models.DateField()),
                ('content', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
