# Generated by Django 2.1.4 on 2019-01-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
