# Generated by Django 2.1.7 on 2019-03-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Content in markdown format')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='Content in markdown format'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, help_text='Content in markdown format'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='content',
            field=models.TextField(blank=True, help_text='Content in markdown format'),
        ),
    ]
