# Generated by Django 2.1.7 on 2019-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190322_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_to_be_finalised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, db_index=True),
        ),
    ]
