# Generated by Django 2.1.4 on 2019-01-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position_af', models.CharField(max_length=300)),
                ('position_en', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=99)),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
                'ordering': ['order'],
            },
        ),
    ]
