# Generated by Django 2.1.7 on 2019-03-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190322_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(db_index=True)),
                ('document', models.FileField(upload_to='newsletters/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
