# Generated by Django 2.1.4 on 2019-01-01 06:15

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_committeemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='images/', verbose_name='Image', width_field='width')),
                ('caption', models.TextField(blank=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.Post')),
            ],
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Research Item', 'verbose_name_plural': 'Research Items'},
        ),
    ]
