# Generated by Django 2.1.4 on 2019-01-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190101_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extract',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
