# Generated by Django 2.2.1 on 2019-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public',
            field=models.BooleanField(default=False, help_text='True if it should be displayed on documents page'),
        ),
    ]
