# Generated by Django 2.1.4 on 2019-01-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_extract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('date_published', models.DateField(help_text='Date on which the document was published', null=True)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('link', models.URLField(blank=True, help_text='Link to document if external file')),
                ('description', models.TextField(blank=True, help_text='Publicly shown text to describe contents of the document')),
                ('notes', models.TextField(blank=True, help_text='Private notes not shown publicly')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='documents',
            field=models.ManyToManyField(related_name='posts', to='core.Document'),
        ),
    ]
