# Generated by Django 2.1.4 on 2019-01-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_published',
            field=models.DateField(blank=True, help_text='Date on which the document was published', null=True),
        ),
    ]
