# Generated by Django 2.1.4 on 2019-01-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190112_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='email_address_public',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
