# Generated by Django 2.1.4 on 2019-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_committeemember_email_address_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timeline',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
