# Generated by Django 2.1.4 on 2019-03-16 06:34

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190126_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='images/', verbose_name='Image', width_field='width')),
                ('caption', models.TextField(blank=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, validators=[core.models.validate_tag]), blank=True, db_index=True, help_text='Comma-seperated list of tags, using only lowercase letters without whitespace', size=None)),
            ],
        ),
    ]
