# Generated by Django 2.1.4 on 2019-03-16 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
