# Generated by Django 2.1.7 on 2019-03-21 13:52

import content.models
import django.contrib.postgres.fields
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('date_published', models.DateField(blank=True, help_text='Date on which the document was published', null=True)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('link', models.URLField(blank=True, help_text='Link to document if external file')),
                ('description', models.TextField(blank=True, help_text='Text to describe contents of the document')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, validators=[content.models.validate_tag]), blank=True, db_index=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='images/', verbose_name='Image', width_field='width')),
                ('caption', models.TextField(blank=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, validators=[content.models.validate_tag]), blank=True, db_index=True, null=True, size=None)),
            ],
        ),
    ]
